### ISSUE TITLE
Bad redirection on lin  1.1 Intro and Setup

### ISSUE THREAD

**Issue by benoitrongeard** [ericwindmill/flutter_by_example#11]
Hello,

Thanks for your formation.

I have a problem with the link on the chapter 1.1 Intro and Setup. It redirect on an other chapter : 2.1 Intro and Overview.

**Comment by ericwindmill** [comment]
Thanks for pointing that out, I will fix as soon as I have time!

**Comment by ericwindmill** [comment]
Fixed. Thanks @benoitrongeard for pointing it out and @wurikiji for fixing!
